# DEVELOPMENT DOCKER FILE
# for use when developing application
# nginx is used as router for all containers
# and is the only container exposed to the host
FROM nginx:alpine

# copy the nginx server configuration
COPY ./nginx_conf/default.conf /etc/nginx/conf.d/default.conf
COPY ./nginx_conf/nginx.conf /etc/nginx/nginx.conf

# copy static content to be served
COPY ./frontend/static/ /usr/share/nginx/html/
