# base python image
FROM python:3.5.7-alpine3.8

# set working directory
WORKDIR '/app'

RUN pip3 install Django


# move backend directory into root of app directory
# OK b/c backend image contains no frontend code
COPY ./ ./
RUN rm ./synth_project/settings_prod.py

EXPOSE 5005
CMD ["python3", "manage.py", "runserver", "0.0.0.0:5005"]
