sudo: required
services:
  - docker

# need to make part files for all of this
before_install:
  - docker build -t "$DOCKER_ID/{}-frontend-test" -f ./frontend/Dockerfile.dev ./frontend
  - docker build -t "$DOCKER_ID/{}-backend-test" -f ./backend/Dockerfile.dev ./backend
  # more builds for diff images to test can be added here

script:
  # -- --coverage is needed to exit upon npm test completion
  - docker run "$DOCKER_ID/{}-frontend-test" npm test -- --coverage
  - docker run "$DOCKER_ID/{}-backend-test" python3 -m unittest discover tests
  # more tests can be added here for diff images

after_success:
  # build our prod docker images for pushing to hub
  - docker build -t "$DOCKER_ID/{}-router" ./nginx
  - docker build -t "$DOCKER_ID/{}-frontend" ./client
  - docker build -t "$DOCKER_ID/{}-backend" ./server
  - docker build -t "$DOCKER_ID/{}-worker" ./worker
  # log in to the docker hub CLI using travis secrets
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push "$DOCKER_ID/[]-router"
  - docker push "$DOCKER_ID/{}-frontend"
  - docker push "$DOCKER_ID/{}-backend"
  - docker push "$DOCKER_ID/{}-worker"
