# Pull base image
FROM node:6.17-alpine

# Set working container path for commands
WORKDIR /usr/my_node_app

# Copy files over
COPY ./package.json ./

# SET UP DEPENDENCIES
RUN npm install && \
    echo 'Attempting to fix vulnerabilities via `npm audit fix`' && \
    npm audit fix

COPY ./ ./

# Default command to run dev environment (nodemon)
CMD ["npm", "run", "dev"]
